function addLines(movie){
    return {
        //default
    "lol":[        
        ["Green", "Stupid Test Code"],
        ["END", null],
    ],
    //bowling
    "BowlOwner1":[
        ["BOWLOWNER" , "Bowling Owner: Hi, welcome to bowling."],
        ["LINGO" , "Lingo: Hi, we're here to bowl for the wunga.. bunga..."],
        ["BOWLOWNER" , "Bowling Owner: The “Super Bowling Wunga Bunga Golden Bowling Ball”."],
        ["LINGO" , "Lingo: Yes."],
        ["BOWLOWNER" , "Bowling Owner: Yeah, Just grab a ball. You get one shot."],
        ["BUDDY" ,  GS.othaStuff.bname + ": Hey you!"],
        ["BOWLOWNER" , "Bowling Owner: Yeah?"],
        ["BUDDY" ,  GS.othaStuff.bname + ": I know you!"],
        ["BOWLOWNER" , "Bowling Owner: Uh, no?"],
        ["BOWLOWNER" , "Bowling Owner: \nI have literally never seen you in my entire life?"],
        ["BUDDY" ,  GS.othaStuff.bname + ": Yes I have! You're that Rico guy!"],
        ["BOWLOWNER" , "Bowling Owner: Who????"],
        ["BUDDY" ,  GS.othaStuff.bname + ": That Rico guy! From that cartoon I saw on the internet!"],
        ["BOWLOWNER" , "Bowling Owner: Look, sir, I think you may have me confused-"],
        ["BOWLOWNER" , "-for someone else?"],
        ["BUDDY" ,  GS.othaStuff.bname + ": But look at this image! You look exactly like him!!"],
        [null , movie.RicoPic],
        ["BOWLOWNER" , "Bowling Owner: What Image??"],
        ["LINGO" , "Lingo: Yeah dude what are you talking about."],
        ["BOWLOWNER" , "Bowling Owner: Look, I told you! I'm not whoever you're talking about, ok?"],
        ["BUDDY" ,  GS.othaStuff.bname + ": Yes you are!! Where's my computer BITCH!"],
        ["BOWLOWNER" , "Bowling Owner: What the?? WHO DO YOU THINK YOU'RE TALKING TO!?"],
        ["LINGO" , "Lingo: Woah woah! Everyone calm down! We'll get a ball ok!."],
        ["BOWLOWNER" , "Bowling Owner: Good, cause when you're done, I want you out of my establishment!!"],
        ["END", null],
        ],
    "GetABall":[
        ["BOWLOWNER" , "Bowling Owner: Go get a ball."],
        ["END", null],
        ],
    "StillHere":[
        ["BOWLOWNER" , "Bowling Owner: Hey! Didn't I tell you kids to scram once you're out?!"],
        ["LINGO" , "Lingo: Uh, we had stuff to do..."],
        ["BUDDY" , GS.othaStuff.bname + ": Yeah, we're just taking our time."],
        ["BOWLOWNER" , "Bowling Owner: Well ok."],
        ["END", null],
    ],

    "NoBalls":[
        [null, "(It seems like the tacky looking vending machine has a lack of bowling balls)"],
        [null, movie.noBowlingBalls],
        ["END", null],
    ],
    "StillNoBalls":[
        [null, "Still no balls"],
        ["END", null],
    ],

    "BowlOwner2":[
        ["LINGO" , "Lingo: Uh sir. There are no bowling balls."],
        ["BOWLOWNER" , "Bowling Owner: Oh yeah."],
        ["BOWLOWNER" , "Bowling Owner: We ran out."],
        ["LINGO" , "Lingo: What? How?"],
        ["BOWLOWNER" , "Bowling Owner: Some red looking things came here and started chewing up all the balls."],
        ["BOWLOWNER" , "Bowling Owner: I shooed them away, but at that point they were basically unuseable."],
        ["BOWLOWNER" , "Bowling Owner: So I just threw 'em out back."],
        ["LINGO" , "Lingo: Don't you have ANY more??"],
        ["BOWLOWNER" , "Bowling Owner: Those were the only 3 we had, sorry."],
        ["LINGO" , "Lingo: What kind of bowling alley has no balls??"],
        ["BOWLOWNER" , "Bowling Owner: Look, you can't bowl anymore, so just get out already."],
        ["LINGO" , "Lingo: We REALLY need to bowl."],
        ["BOWLOWNER", "Bowling Owner: Will you just get out already?!"],
        [null, movie.moveInPins],
        ["PIN", "Pin Boss: No one's going anywhere!"],
        ["LINGO" , "Lingo: ..."],
        ["LINGO" , "Lingo: Are those talking pins."],
        ["PINS", "Pin Gang: WE ARE LINGO BINGO!"],
        ["BUDDY", GS.othaStuff.bname + ": No, I am!!"],
        ["", "Lingo: None of you are!"],
        ["", "Pin #2: Did you hear that boss? He thinks he's the real deal!"],
        ["", "Pin Boss: Yeah, I hear him all right!"],
        ["", "Pin Boss: So, I hear you're looking to knock us down, ain't that right mister?"],
        ["", "Lingo: Uh, Maybe?"],
        ["", "Pin Boss: Well, we pins are tired of you stupid humans kicking us in dirt!"],
        ["", "Pin Boss: With your stupid \"BOWLING BALLS\" and your insulting win screens!"],
        ["", "Pin Boss: For centuries, us pins have been run under the gutter! "],
        ["", "Pin Boss: But now, it ends today! Today, we take the hand of the bowler! Today, we- "],
        ["", "Pin #3: I though our deal was that we were lingo bingo."],
        ["", "Pin Boss: ..."],
        //["", ""],
        ["", "Pin Boss: WHO JUST INTERRUPTED ME."],
        ["", "Pin #3: ..."],
        ["", "Pin #5: ... "],
        ["", "Pin #4: ..."],
        ["", "Pin Boss: Everyone! Recite the numba one BIG RULE!"],
        ["", "Pin Gang: Never interrupt the boss when he's making a speech."],
        ["", "Pin Gang: Even when he's reciting somethin' really stupid."],
        ["", "Pin Boss: So who's did it?! Or I'll kill the lot of you for calling me stupid!"],
        ["", "Pin #2: ..."],
        ["", "Pin #6: It was 3!"],
        ["", "Pin Boss: Oh boy, when I get done slaugthering these kiddos ova' here!"],
        ["", "Lingo: Gulp!"],
        ["", "Pin #3: Gulp!"],
        ["", "Pin Boss: Everyone, ready your chompers!"],
        ["", "Lingo: Those guys aren't actually gonna kill us, right?"],
        ["", "Pin Boss: READY!!"],
        ["", "Lingo: Crap, what do we do!"],
        ["", GS.othaStuff.bname + ": I have an idea!"],
        ["", "Lingo: What?!"],
        ["", GS.othaStuff.bname + ": Remember when you threw me at that monster?"],
        ["", "Lingo: Um, yeah? What's your point?"],
        ["", "Pin Boss: Aim!"],
        ["", GS.othaStuff.bname + ": How good are you at bowling?"],
        ["", "Lingo: What do you mean?"],
        ["", GS.othaStuff.bname + ": Just follow my lead!"],
        ["", "Pin Boss: Fire!"],
        [null, movie.lights],
        [null, movie.setupbattle],
        ["END", null],
        `
            GS.othaStuff.bname + ": No, I am!!"
            Lingo: None of you are!
            Pin #2: Did you hear that boss? He thinks he's the real deal!
            Pin Boss: Yeah, I hear him all right!
            Pin Boss: So, I hear you're looking to knock us down, ain't that right mister?
            Lingo: Uh, Maybe?
            Pin Boss: Well, we pins are tired of you stupid humans kicking us in dirt!
            Pin Boss: With your stupid \"BOWLING BALLS\" and your insulting win screens!
            Pin Boss: For centuries, us pins have been run under the gutter! 
            Pin Boss: But now, it ends today! Today, we take the hand of the bowler! Today, we- 
            Pin #3: I though our deal was that we were lingo bingo.
            Pin Boss: ...
            movie.pinSnapback
            Pin Boss: WHO JUST INTERRUPTED ME.
            Pin #3: ...
            Pin #5: ... 
            Pin #4: ...
            Pin Boss: Everyone! Recite the numba one BIG RULE!
            Pin Gang: Never interrupt the boss when he's making a speech.
            Pin Gang: Even when he's reciting somethin' really stupid.
            Pin Boss: So who's did it?! Or I'll kill the lot of you for calling me stupid!
            Pin #2: ...
            Pin #6: It was 3!
            Pin Boss: Oh boy, when I get done slaugthering these kiddos ova' here!
            Lingo: Gulp!
            Pin #3: Gulp!
            Pin Boss: Kiddos! Prepare to be destroyed!
            Lingo: Those guys aren't actually gonna kill us, right?
            Pin Boss: Everyone, ready your chompers!
            Lingo: Crap, what do we do!
            GS.othaStuff.bname + ": I have an idea!"
            Lingo: What?!
            movie.Buddyidea
            GS.othaStuff.bname + ": Remember when you threw me at those guys?"
            Lingo: Um, yeah? What's your point?
            Pin Boss: Aim!
            GS.othaStuff.bname + ": How good are you at bowling?"
            Lingo: What do you mean?
            GS.othaStuff.bname + ": Just follow my lead!"
            Pin Boss: Fire!
        `
    ],
    "BowlOwner3":[
        ["BOWLOWNER", "You still have to leave."],
        ["END", null],
    ],
    "SaveBowling":[
        [null, "TEXT TO BE ADDED"],
        //["BOWLOWNER", "Bowling Owner: Woah! Nice job! You really saved me a lawsuit there!"],
        //[null, movie.trophyFall],
        //["BUDDY" , GS.othaStuff.bname + ":Does that mean we win?"],
        //["BOWLOWNER", "Bowling Owner:...."],
        //["LINGO" , "Lingo: Come on man."],
        //["BOWLOWNER", "Bowling Owner: Ugh! Fine! Since you technically knocked all the pins, I guess you win."],
        //["BOWLOWNER", "Bowling Owner: As the owner of this place, I award you with the..(UFINISHED)"],
        [null, movie.getTrophy],
        [null, "You got the trophy!"],
        ["END", null],
        
    ],
    "Pins":[
        [null, movie.lights],
        [null, movie.setupbattle],
        ["END", null],
    ], 
    //luke
    "StartBowlingQuest":[
        ["LUKE" , "LUKE:You, what’s up bro?"],
        ["LINGO" , "LINGO: Uh, hey.. Before I say anything can I ask what’s with your house?"],
        ["LUKE" , "LUKE: Like the paint job? It really reflects my bad side, you know?"],
        ["LINGO" , "LINGO: Right...\nSo... you haven’t noticed anything strange"],
        ["LINGO" , "...happening, have you?"],
        ["LUKE" , "LUKE: Well, this one really ugly looking guy started charging at me yelling \“I AM LINGO\” or some stuff."],
        ["LUKE" , "LINGO: LUKE: But of course  I beat the sucka up. He went flying! Haha!"],
        ["LINGO" , "LINGO: Did it happen to have my PC on it?"],
        ["LINGO" , "LINGO: Because my PC was ripped straight from my wall."],
        ["LUKE" , " LUKE: That sucks dude! Well, there have been a lot of weird folks going around, so I’ll keep an eye out."],
        ["LINGO" , "LINGO: I see."],
        ["LUKE" , "LUKE: Hey! Did I tell you about the new ugly convention that opened recently?"],
        ["LINGO" , "LINGO: No. Maybe later, I gotta go find my computer."],
        ["LUKE" , "LUKE: I think it’s called the \”Lingo Bingo Museum\” or something."],
        ["BUDDY" , GS.othaStuff.bname + " Hey that’s m-"],
        ["LINGO" , "LINGO: What."],
        ["LUKE" , "LUKE: Yeah, I know right? Who would wanna spend their time there to look at some weird red hatted guy?"],
        ["BUDDY" , GS.othaStuff.bname + " HEY!!"],
        ["LINGO" , "LINGO: (I should probably start there first)."],
        ["LINGO" , "LINGO: Hypothetically where would we find this place."],
        ["LUKE" , "LUKE: Sorry man, it’s in town, but the police have got the bridge all locked up. No idea why."],
        ["LINGO" , "LINGO: Ok but I REALLY need to get over there.."],
        ["LUKE" , "LUKE: Well, I MIGHT be able to help you.."],
        ["LUKE" , "LUKE: Ok listen up. I may or my not have the key to the city, don’t ask how."],
        ["LUKE" , "LUKE: And I can totally give it to you if you win me the SUPER BOWLING WUNGA BUNGA GOLDEN BOWLING BOWL k’bob."],
        ["LINGO" , "LINGO: What’s that?."],
        ["LUKE" , "LUKE: It’s only the greatest bowling prize! They’re hosting it at the bowling alley! And I want it!."],
        ["LUKE" , "LUKE: But I got banned…."],
        ["LUKE" , "..again.."],
        ["LINGO" , "LINGO: Alright, I’ll see what I can do."],
        ["END", null],
    ],
    "GiveTrophy":[
        ["LINGO", "Lingo: Here you go, your trophy."],
        ["LUKE", "Luke: Woah! You got it!"],
        ["LINGO", "Lingo: Don't sweat it. Now about that key.."],
        ["LUKE", "Luke: Wait! Before I give you this key, I need you do do me ONE more favor."],
        ["LINGO", "Lingo: Ugh.. really?"],
        ["LUKE", "Luke: It'll be quick ok?"],
        ["LINGO", "Lingo: FINE."],
        ["LUKE", "Luke: I need you to go down to ORANGETOWN and get me a gumball."],
        ["LINGO", "Lingo: What's ORANGETOWN?"],
        ["LUKE", "Luke: You don't know? It's just past the bowling alley."],
        ["BUDDY", GS.othaStuff.bname + " YEAH, DUH."],
        ["LUKE", "Luke: DUH."],
        ["BUDDY", GS.othaStuff.bname + " YEAH, DUH!"],
        ["LUKE", "Luke: DUH!"],
        ["LINGOyell", "Lingo: OK I'M GOING!!."],
        ["END", null],
    ],
    "DoinChewin":[
        ["LUKE", "Lucas: I'm doin' for a chewing."],
        ["END", null],       
    ],
    "WinningSoHard":[
        ["LUKE" , "LUKE: I'm winning that trophy so hard rn."],
        ["END", null],
    ],
    "NothingMuch":[
        ["Blueangry", "NothingMuch"],
        ["END", null],
    ],
    
    //worried boy quest
    "StartWKQuest":[
        [null , movie.worriedKidFlip],
        ["LINGO" , "Lingo: What’s wrong man?."],
        ["WORRIEDKID" , "WorriedKid: I really need to find my little brother!"],
        ["LINGO" , "Lingo: Why?"],
        ["WORRIEDKID" , "WorriedKid: My brother has something I really need!"],
        ["WORRIEDKID" , "WorriedKid: And I have to get it so I can get something from someone else!!"],
        [null , movie.endBallQuestEarly],
        ["LINGO" , "Lingo: I'm sorry what are you looking for?"],
        ["WORRIEDKID" , "WorriedKid: I really need to find my little brother!"],
        ["BUDDY" , "Lingo: Hi! I’m Lingo Bingo! And I’ll help you find your thing!"],
        ["LINGO" , "Lingo: (No you're not.)"],
        ["WORRIEDKID" , "WorriedKid: Woah really? I’m a big fan!"],
        ["LINGO" , "Lingo: Noooooo you're not!."],
        ["LINGO" , "Lingo: Look, we'll find your brother ok."],
        ["WORRIEDKID" , "WorriedKid: Ok,cool!"],
        ["WORRIEDKID" , "WorriedKid: I think he’s hiding in one of these trees somewhere!"],
        [null , movie.worriedKidFlip],
        ["END", null],
    ],
    
    "GetTickets":[

        ["LINGO" , "Lingo: Um, is this what you were looking for?"],
        ["WORRIEDKID" , "The  ball! Thanks a lot pal!"],
        ["BOTH" , "You're welcome."],
        ["BOTHLOOK" , "..."],
        ["LUCAS" , "Lucas: Finally, about time!!"],
        ["WORRIEDKID" , "So can I get those tickets now??!"],
        ["LUCAS" , "Lucas: HHHHHMMMMMMMMMM no!"],
        ["WORRIEDKID" , "What!!!???"],
        ["LUCAS" , "Lucas: You had me waiting for ages!"],
        ["LUCAS" , "Lucas: Hey man, take these off my hands will you?"],
        [null , "You got the tickets!"],
        ["WORRIEDKID" , "Can I have those back please?"],
        ["LINGO" , "Lingo: Uhhhh...."],
        ["END", null],
    ],
    "AfterTakingTickets":[
        [null , movie.worriedKidFlipLeft],
        ["WORRIEDKID" , "Yeah I'm just gonna ignore you and stare at this tree."],
        [null , movie.worriedKidFlip],
        ["END", null],
    ],
    "WorriedKidTreeStare":[
        [null , movie.worriedKidFlip],
        ["WorriedBro", "I can't climbs trees."],
        ["WorriedBro", "So I'm just going to intensely stare at this tree."],
        ["WorriedBro", "Hopefully he's in this one and he'll come down."],
        [null , movie.worriedKidFlip],
        ["END", null],
    ],
    "FindBoy":[
        ["LINGO" , "Lingo: Hey kid! Come down!"],
        ["SMARTKID" , "No way!"],
        ["LINGO" , "Lingo: Come on, playtime's over."],
        ["SMARTKID" , "You just want this ball! I'm not giving it back!"],
        ["BUDDY" , "Lingo: If you don't come down, I'll shoot a lazer at you."],
        ["BUDDY" , "Nuh uh! People can't shoot lazers!"],
        ["BUDDY" , "..."],
        ["BUDDY" , "initiating Lazer Countdown In 3..."],
        ["LINGO" , "Lingo: What the-!!??"],
        ["BUDDY" , "Lingo: 2..."],
        ["LINGO" , "Stop!!"],
        ["BUDDY" , "..."],
        ["LINGO" , "..."],
        ["BUDDY" , "..."],
        ["BUDDY" , "3210-"],
        ["SMARTKID" , "Ok Fine!!"],
        [null, movie.kidBounce],
        ["SMARTKID" , "Rodger: You know, us kids aren't all that stupid!"],
        ["SMARTKID" , "Rodger: Not that I thought you were gonna shoot me."],
        ["SMARTKID" , "Rodger: Here you go!"],
        [null , movie.getBeachBall],
        [null , "You got the Beachball!"],
        ["SMARTKID" , "Rodger: See you later!"],
        [null , movie.kidRunToShop],
        ["END", null],
    ],
    "NoBoy":[
        ["VANNESA" , "Vannesa: Ain't nothing but little old me!"],
        ["VANNESA" , "Vannesa: Vannesa the tree!"],
        ["END", null],
    ],
    "NthHere":[
        [null , "Nothing here but a tree."],
        ["END", null],
    ],   
    "Tom":[
        ["TREE" , "Tom: Hi! I'm Tom the Tree!"],
        ["TREE" , "Tom: Have you met my friend Vanessa? She's great."],
        ["END", null],
    ],     
    "Tom2":[
        ["TREE" , "Tom: Fun fact! Did you know that all trees are connected?."],
        ["TREE" , "Tom: By one singular being that lives underground?"],
        ["TREE" , "Tom: Yet somehow, all of us trees have a mind of our own?"],
        ["TREE" , "Tom: It's true!"],
        ["TREE" , "Tom: Me and my fiance like to talk about this sometimes."],
        ["LINGO" , "Lingo:?????"],
        ["END", null],
    ], 
    "TestBounce":[
        ["SMARTKID","Rodger: My bounce I love bouncing."],
        [null, movie.kidBounce],
        ["END", null],
    ],
    //orange
    "RegularGumballTB":[
        [null,"(A gumball machine.)"],
        [null,"(It appears that this gumball machine is full of oranges.)"],
        ["LINGO","Lingo: It appears that this gumball machine is full of oranges."],
        ["BUDDY", GS.othaStuff.bname + ": Wow, how interesting!"],
        ["END", null],
    ],
    "ComicStandTB":[
        [null,"(\"The Orangey Adventures of Orangeman\")"],
        [null,"(An array of brightly orange colored comicbooks sits beneath the sign.)"],
        [null,"(It's so bright that your eyes kind of hurt.)"],
        ["END", null],
    ],
    "OTBackdoorTB":[
        ["OrangeGuyHappy","OrangeGuy: Sorry, employees only back there!"],
        ["BUDDY", GS.othaStuff.bname + ": Darn!"],
        ["END", null],
    ],
    "OrangeGuyTB":[
        ["OGhappy","OrangeGuy: Welcome to OrangeTown! The greatest orange themed convience store-"],
        ["OGhappy","-in the neighborhood!!"],
        ["LINGOcon","Lingo: Really? Because I've never heard of you?"],
        ["OGwor","OrangeGuy: Surely you've heard of my amazing orange soda?"],
        ["LINGO","Lingo: Uh, not really."],
        ["OGwor","OrangeGuy: My chewy gooey orange candy!"],
        ["LINGO","Lingo: No."],
        ["OGwor","OrangeGuy: Come on, really?! What about you red kid?"],
        ["BUDDY", GS.othaStuff.bname + ": Huh?"],
        ["BUDDY", GS.othaStuff.bname + ": Sorry I wasn't listening, I was trying to figure out who this guy is."],
        ["OGsad","OrangeGuy: Sigh, I'll admit. I'm kinda just starting out."],
        ["OGsad","OrangeGuy: I would have thought more people would find my place by now."],
        ["BUDDY", GS.othaStuff.bname + ": Then what's a weirdo like you doing all the way out here?"],
        ["OGwor","OrangeGuy: Hey! This is a really good spot for my oranges to grow!"],
        ["LINGO","Lingo: He does have a point. How is anybody supposed to find you out here?"],
        ["LINGOcon","Lingo: And more importantly, what's with the orange theming??"],
        ["OGwor","OrangeGuy: Ok, you kids are asking too many questions!"],
        ["OGwor","OrangeGuy: Here! Try my special orange yogurt!"],
        ["LINGOthinking","Lingo: ..."],
        ["LINGOwoah","Lingo: Woah! This tastes great!"],
        ["BUDDY", GS.othaStuff.bname + ": I want more!"],
        ["OGhappy","OrangeGuy:See, now you're getting it!"],
        ["OGhappy","OrangeGuy: Hey, and guess what?"],
        ["OGhappy","OrangeGuy: The \"BIG MALL\" across town offered me a section in one of their stores!"],
        ["OGhappy","OrangeGuy: EVERYONE'S gonna want a piece of me once they taste my stuff!"],
        ["LINGOwoahhappy","Lingo: That's great man-"],
        ["LINGO","Lingo: ..."],
        ["LINGO","Lingo: Don't say it like that."],
        ["OGfavor","OrangeGuy: Since you're here..\n can I ask you a little favor?"],
        ["OGhappy","OrangeGuy: You see, The Big Mall wants to try some of my products."],
        ["OGhappy","OrangeGuy: But, I can't deliver them right now!."],
        ["OGwince","OrangeGuy: I'm not sure if you've heard, but there are some weird creatues appearing out of nowhere."],
        ["OGhappy","OrangeGuy: I think I saw one of them entering my shop! It was scary!"],
        ["OGhappy","OrangeGuy: So I'm gonna set some traps up to capture it!"],
        ["OGhappy","OrangeGuy: So, um... can YOU deliver my products for me?"],
        ["BUDDY", GS.othaStuff.bname + ": Yes! Of course! Absolutely."],
        ["OGhappy","OrangeGuy: Really? Thanks!"],
        ["LINGO","Lingo: Ok."],
        [null , movie.getProducts],
        [null,"You got the crate of oranges!"],
        ["END", null],
    ],
    "2Customers":[
        ["LINGO","Lingo: How long have you been open?"],
        ["END", null],
    ],
    "BabyDoorTB":[
        [null, "(A small gate baracades you from going behind the counter.)"],
        [null, "(Presumably to keep weirdos like you away.)"],
        ["BUDDY", GS.othaStuff.bname + ": Hey!"],
        ["LINGO","Lingo: What?"],
        ["END", null],
    ],
    "ItLooksAtYou":[
        [null,"*Something about this trashbin really bothers you two."],
        ["BUDDY", GS.othaStuff.bname + ": ..."],
        ["LINGODist","Lingo: ..."],
        [null,"*For some reason, it looks hungry."],
        ["END", null],
    ],
    "QuarterGot":[        
        [null,"*It's waiting."],
        [null,"*You feed the trashbin an orange."],
        [null,"*A quarter spits out."],
        ["LINGO","Lingo: (Why did i do that??)"],
        ["END", null],
    ],
    "More":[
        [null,"*Actually no, \"you\" feed it all the oranges."],
        ["LINGOyell", GS.othaStuff.bname + ": Why would you do that?!"],
        ["BUDDY","BUDDY: It looked hungry!."],

        ["END", null],
    ],
    "ItLooksAtYou2":[        
        [null,"*Stop looking at it."],
        ["END", null],
    ],
    "Gumhing":[
        ["BUDDY", GS.othaStuff.bname + ":Oh boy! Gum time!"],
        [null, "*25 cents was put into the machine."],
        ["LINGO","Lingo: ..."],
        ["LINGO","Lingo: I think it's broken."],
        [null,movie.gumhingShake],
        ["BUDDY", GS.othaStuff.bname + ":I think something's coming out!"],
        [null, movie.gumhingRise],
        ["GUMMACHINE","!!!!!!!!!!!!!!!!!!!!"],
        ["LINGO","Lingo: What is that."],
        ["GUMMACHINE","!!!!!!!!!!!!!!!!!!!!"],
        ["BUDDY", GS.othaStuff.bname + ": I think it said.."],
        ["BUDDY", GS.othaStuff.bname + ": \"I AM LINGO!\""],
        //taking it off [null,"movie.tryToPullGumhing],
        ["BUDDY", GS.othaStuff.bname + ": I think it's stuck."],
        ["LINGO","Lingo: ...."],
        ["LINGO","Lingo: Ok. Here's what we're gonna do."],
        ["LINGO","Lingo: We're gonna go home, contact the authorities, and..."],
        ["GUMMACHINE","!!!!!!!!!!!!!!!!!!!!"],
        ["LINGO","Lingo: What did it say now?"],
        ["BUDDY", GS.othaStuff.bname + ": I think it said.."],      
        ["BUDDY", GS.othaStuff.bname + ": Too late!!"],   
        [null, movie.lights],      
        [null, movie.setupbattle],
        ["END", null],
    ],


    //landfill
    "Tweezers":[
        ["BUDDY", GS.othaStuff.bname + ": Tweezers! I'll take toes!"],
        ["LINGO","Lingo: What?"],
        ["BUDDY", GS.othaStuff.bname + ":I mean, I'll take those!"],
        ["LINGO","Lingo: Whatever you say."],
        [null,movie.getTweezers],
        [null,"*You got the tweezers."],
        ["END",null],
    ],
    
	"CantBeach":[
		[null, "???: HELP!! HELP!!"],
		["BUDDY", GS.othaStuff.bname + ": Hey! Looks like someone's crying for help!"],
		["LINGO", "Lingo: Yo! Are you ok?"],
		[null, "???: Uh, yes.. just a bit stuck though."],
		[null, "???: Do you think you could come over here?"],
		["LINGO", "Lingo: Yeah, sure!"],
		["LINGO", "Lingo: Huh? That\'s strange, the gate\'s locked."],
		["BUDDY", GS.othaStuff.bname + ": Looks like it's up to the duo to fix the gate!"],
		["LINGO", "Lingo: We are not a duo, but ok."],
		["LINGO", GS.othaStuff.bname + ": Hang tight stranger!"],
		["END", null],
    ],

	"StillCantBeach":[
		[null, "*The gate is locked"],
		["END", null],
    ],
	"CanBeach":[
		["BUDDY", GS.othaStuff.bname + ": Wapow!"],
		["LINGO", "Lingo: What are you doing?"],
		["BUDDY", GS.othaStuff.bname + ": Opening the gate!"],
		["LINGO", "Lingo: Dude, you are not breaking the gate with those tweezers."],
        [null, movie.beachBarrier],
		[null, "*CLANG!!"],
		["LINGOyell", "Lingo: Dude what the?! You broke the gate!!"],
		["BUDDY", GS.othaStuff.bname + ": Yes! Now we can get through!"],
        ["LINGOyell", "Lingo: I'm pretty sure that's GOVERNMENT PROPERTY??"],
		["BUDDY", GS.othaStuff.bname + ": Oh relax. I'm sure someone will glue it back together."],
        ["BUDDY", GS.othaStuff.bname + ": For someone pretending to be me you sure are dramatic."],
		[null, "???: HELP!! HELP!!"],
		["END", null],
    ],
}
}